% Util function used to help in the computation of matrix V in the
% compute_IntrinsicParams() function.

function vij = calculate_vij(i,j, H)
    vij = [H(1,i)*H(1,j); ... 
           H(1,i)*H(2,j) + H(2,i)*H(1,j); ...
           H(2,i)*H(2,j); ...
           H(3,i)*H(1,j) + H(1,i)*H(3,j); ...
           H(3,i)*H(2,j) + H(2,i)*H(3,j); ...
           H(3,i)*H(3,j)];
end